package com.knowledgeassessor.persistence;

// Generated Sep 13, 2012 5:44:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * exam generated by hbm2java
 */
@Entity
@Table(name = "EXAM")
public class exam implements java.io.Serializable {

	private int id;
	private String examStatus;
	private int numberOfQuestions;
	private int correctlyAnswered;

	public exam() {
	}

	public exam(String examStatus, int numberOfQuestions, int correctlyAnswered) {
		this.examStatus = examStatus;
		this.numberOfQuestions = numberOfQuestions;
		this.correctlyAnswered = correctlyAnswered;
	}

	@Id
	@GeneratedValue
	@Column(name = "exam_id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "exam_status")
	public String getExamStatus() {
		return this.examStatus;
	}

	public void setExamStatus(String examStatus) {
		this.examStatus = examStatus;
	}

	@Column(name = "numberof_questions")
	public int getNumberOfQuestions() {
		return this.numberOfQuestions;
	}

	public void setNumberOfQuestions(int numberOfQuestions) {
		this.numberOfQuestions = numberOfQuestions;
	}

	@Column(name = "correctly_answered")
	public int getCorrectlyAnswered() {
		return this.correctlyAnswered;
	}

	public void setCorrectlyAnswered(int correctlyAnswered) {
		this.correctlyAnswered = correctlyAnswered;
	}

}
