SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`LKUP_LANGUAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LKUP_LANGUAGE` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`LKUP_LANGUAGE` (
  `LANGUAGE_ID` INT NOT NULL AUTO_INCREMENT ,
  `LANGUAGE_CODE` VARCHAR(45) NOT NULL ,
  `DESCRIPTION` VARCHAR(45) NULL ,
  PRIMARY KEY (`LANGUAGE_ID`, `LANGUAGE_CODE`) ,
  UNIQUE INDEX `LANGUAGE_ID_UNIQUE` (`LANGUAGE_ID` ASC) ,
  UNIQUE INDEX `LANGUAGE_CODE_UNIQUE` (`LANGUAGE_CODE` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LKUP_SUBTOPIC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LKUP_SUBTOPIC` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`LKUP_SUBTOPIC` (
  `LKUP_SUBTOPIC_ID` INT NOT NULL AUTO_INCREMENT ,
  `SUBTOPIC_CODE` VARCHAR(45) NOT NULL ,
  `DESCRIPTION` VARCHAR(45) NULL ,
  PRIMARY KEY (`LKUP_SUBTOPIC_ID`, `SUBTOPIC_CODE`) ,
  UNIQUE INDEX `SUBTOPIC_CODE_UNIQUE` (`SUBTOPIC_CODE` ASC) ,
  UNIQUE INDEX `LKUP_SUBTOPIC_ID_UNIQUE` (`LKUP_SUBTOPIC_ID` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`XREF_LANGUAGE_SUBTOPIC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`XREF_LANGUAGE_SUBTOPIC` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`XREF_LANGUAGE_SUBTOPIC` (
  `LANGUAGE_CODE` VARCHAR(45) NOT NULL ,
  `SUBTOPIC_CODE` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`LANGUAGE_CODE`, `SUBTOPIC_CODE`) ,
  INDEX `fk_LKUP_LANGUAGE_has_LKUP_SUBTOPIC_LKUP_SUBTOPIC1_idx` (`SUBTOPIC_CODE` ASC) ,
  INDEX `fk_LKUP_LANGUAGE_has_LKUP_SUBTOPIC_LKUP_LANGUAGE1_idx` (`LANGUAGE_CODE` ASC) ,
  CONSTRAINT `fk_LKUP_LANGUAGE_has_LKUP_SUBTOPIC_LKUP_LANGUAGE1`
    FOREIGN KEY (`LANGUAGE_CODE` )
    REFERENCES `mydb`.`LKUP_LANGUAGE` (`LANGUAGE_CODE` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LKUP_LANGUAGE_has_LKUP_SUBTOPIC_LKUP_SUBTOPIC1`
    FOREIGN KEY (`SUBTOPIC_CODE` )
    REFERENCES `mydb`.`LKUP_SUBTOPIC` (`SUBTOPIC_CODE` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QUESTIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`QUESTIONS` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`QUESTIONS` (
  `QUESTIONS_ID` INT NOT NULL AUTO_INCREMENT ,
  `QUESTION` VARCHAR(255) NULL ,
  `LANGUAGE_CODE` VARCHAR(45) NOT NULL ,
  `SUBTOPIC_CODE` VARCHAR(45) NOT NULL ,
  `CREATE_USER` VARCHAR(45) NULL ,
  `CREATE_DATETIME` DATETIME NULL ,
  `MOD_USER` VARCHAR(45) NULL ,
  `MOD_DATETIME` DATETIME NULL ,
  PRIMARY KEY (`QUESTIONS_ID`) ,
  INDEX `fk_QUESTIONS_XREF_LANGUAGE_SUBTOPIC1_idx` (`LANGUAGE_CODE` ASC, `SUBTOPIC_CODE` ASC) ,
  CONSTRAINT `fk_QUESTIONS_XREF_LANGUAGE_SUBTOPIC1`
    FOREIGN KEY (`LANGUAGE_CODE` , `SUBTOPIC_CODE` )
    REFERENCES `mydb`.`XREF_LANGUAGE_SUBTOPIC` (`LANGUAGE_CODE` , `SUBTOPIC_CODE` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ANSWERS_KEY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ANSWERS_KEY` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`ANSWERS_KEY` (
  `ANSWERS_KEY_ID` INT NOT NULL AUTO_INCREMENT ,
  `DESCRIPTION` VARCHAR(255) NULL ,
  `STATUS` INT NULL ,
  `CREATE_USER` VARCHAR(45) NULL ,
  `CREATE_DATETIME` DATETIME NULL ,
  `MOD_USER` VARCHAR(45) NULL ,
  `MOD_DATETIME` DATETIME NULL ,
  `QUESTIONS_ID` INT NOT NULL ,
  PRIMARY KEY (`ANSWERS_KEY_ID`) ,
  INDEX `fk_ANSWERS_KEY_QUESTIONS1_idx` (`QUESTIONS_ID` ASC) ,
  CONSTRAINT `fk_ANSWERS_KEY_QUESTIONS1`
    FOREIGN KEY (`QUESTIONS_ID` )
    REFERENCES `mydb`.`QUESTIONS` (`QUESTIONS_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
